// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rjwihooxmfuetkcuxnhk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJqd2lob294bWZ1ZXRrY3V4bmhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwNjQ3NDMsImV4cCI6MjA3MTY0MDc0M30.hNZvSJ7dtGHN0f3PCsrNP-iJZ98Cv6_ivASb3EPe3W4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});